chdir: /var/www/haccast
pid: /var/www/haccast/tmp/pids/thin.pid
log: log/thin.log
servers: 2
port: 3000
timeout: 60
max_conns: 2048
max_persistent_conns: 1024
require: []
wait: 60
threaded: true
no-epoll: true
threadpool_size: 400
daemonize: true
environment: production
socket: /var/www/haccast/tmp/thin.sock
chdir: /var/www/haccast
user: root
group: root
onebyone: true